# Generated by Django 5.2.7 on 2025-10-21 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('PRUEBA', 'Prueba'), ('BASICO-M', 'Básico-M'), ('PREMIUM-M', 'Premium-M'), ('BASICO-A', 'Básico-A'), ('PREMIUM-A', 'Premium-A')], max_length=50, unique=True, verbose_name='Nombre del Plan')),
                ('precio_mensual', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Mensual')),
                ('limite_usuarios', models.IntegerField(default=5, verbose_name='Límite de Usuarios (Staff)')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('dias_prueba', models.IntegerField(default=0, help_text='Duración en días para planes de prueba. 0 para planes de pago.')),
                ('stripe_price_id', models.CharField(blank=True, help_text='ID del objeto Price de Stripe', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Plan de Suscripción',
                'verbose_name_plural': 'Planes de Suscripción',
            },
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Tienda/Empresa')),
                ('fecha_inicio_servicio', models.DateField(auto_now_add=True, verbose_name='Fecha de Inicio')),
                ('fecha_proximo_cobro', models.DateField(blank=True, null=True, verbose_name='Próximo Cobro')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('CANCELADO', 'Cancelado'), ('PRUEBA', 'Prueba')], default='ACTIVO', max_length=20, verbose_name='Estado de Suscripción')),
            ],
            options={
                'verbose_name': 'Tienda (Tenant)',
                'verbose_name_plural': 'Tiendas (Tenants)',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TiendaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asociacion', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente de Tienda',
                'verbose_name_plural': 'Clientes de Tiendas',
            },
        ),
        migrations.CreateModel(
            name='PagoSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID de Payment Intent de Stripe')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Total')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Emisión')),
                ('fecha_pago', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('FALLIDO', 'Fallido')], default='PAGADO', max_length=20, verbose_name='Estado del Pago')),
                ('plan_pagado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='saas.plansuscripcion', verbose_name='Plan Pagado')),
            ],
            options={
                'verbose_name': 'Pago de Suscripción',
                'verbose_name_plural': 'Pagos de Suscripción',
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
