# Generated by Django 5.2.7 on 2025-10-21 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='admin_contacto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tienda_administrada', to=settings.AUTH_USER_MODEL, verbose_name='Admin de Contacto'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tiendas', to='saas.plansuscripcion', verbose_name='Plan Contratado'),
        ),
        migrations.AddField(
            model_name='pagosuscripcion',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_suscripcion', to='saas.tienda', verbose_name='Tienda'),
        ),
        migrations.AddField(
            model_name='tiendacliente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tiendacliente',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saas.tienda'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='clientes',
            field=models.ManyToManyField(related_name='tiendas_como_cliente', through='saas.TiendaCliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='tiendacliente',
            unique_together={('tienda', 'cliente')},
        ),
    ]
