# Generated by Django 5.2.7 on 2025-11-07 15:14

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='banner',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='banners_tiendas/'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='descripcion_corta',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tienda',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='logos_tiendas/'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='rubro',
            field=models.CharField(blank=True, default='General', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tienda',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
