# Generated by Django 5.2.7 on 2025-10-19 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansuscripcion',
            name='dias_prueba',
            field=models.IntegerField(default=0, help_text='Duración en días para planes de prueba. 0 para planes de pago.'),
        ),
        migrations.AlterField(
            model_name='plansuscripcion',
            name='nombre',
            field=models.CharField(choices=[('PRUEBA', 'Prueba'), ('BASICO-M', 'Básico-M'), ('PREMIUM-M', 'Premium-M'), ('BASICO-A', 'Básico-A'), ('PREMIUM-A', 'Premium-A')], max_length=50, unique=True, verbose_name='Nombre del Plan'),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='fecha_proximo_cobro',
            field=models.DateField(blank=True, null=True, verbose_name='Próximo Cobro'),
        ),
    ]
