# Generated by Django 5.2.7 on 2025-10-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0003_plansuscripcion_dias_prueba_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansuscripcion',
            name='stripe_price_id',
            field=models.CharField(blank=True, help_text='ID del objeto Price de Stripe', max_length=100, null=True),
        ),
    ]
