# Generated by Django 5.2.7 on 2025-10-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='genero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
