# Generated by Django 5.2.7 on 2025-10-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='genero',
            field=models.CharField(blank=True, choices=[('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino'), ('OTRO', 'Otro')], max_length=20, null=True),
        ),
    ]
