# Generated by Django 5.2.7 on 2025-11-06 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nit',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='razon_social',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
