# Generated by Django 5.2.7 on 2025-11-12 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_cliente_nit_cliente_razon_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='puntos_acumulados',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Puntos_Acumulados'),
        ),
    ]
