# Generated by Django 5.2.7 on 2025-11-04 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comercial', '0001_initial'),
        ('saas', '0002_initial'),
        ('users', '0004_alter_userprofile_foto_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Venta')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Venta')),
                ('estado', models.CharField(choices=[('PROCESADA', 'Procesada'), ('ENVIADA', 'Enviada'), ('ENTREGADA', 'Entregada'), ('CANCELADA', 'Cancelada')], default='PROCESADA', max_length=50)),
                ('carrito', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='venta_carrito', to='comercial.carrito')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='users.cliente')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='saas.tienda')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_asignadas', to='users.vendedor')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha_venta'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID Payment Intent (Stripe)')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Total')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado'), ('FALLIDO', 'Fallido'), ('REEMBOLSADO', 'Reembolsado')], default='PENDIENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_recibidos', to='saas.tienda')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_entrega', models.TextField(verbose_name='Dirección de Entrega')),
                ('estado', models.CharField(choices=[('EN_PREPARACION', 'En preparación'), ('EN_CAMINO', 'En camino'), ('ENTREGADO', 'Entregado'), ('INCIDENCIA', 'Incidencia')], default='EN_PREPARACION', max_length=20)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envios_realizados', to='saas.tienda')),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='envio', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Envío',
                'verbose_name_plural': 'Envíos',
            },
        ),
        migrations.CreateModel(
            name='Detalle_Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_historico', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Histórico')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_vendidos', to='comercial.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Venta',
            },
        ),
    ]
