# Generated by Django 5.2.7 on 2025-11-11 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='detalle_carrito',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
