# Generated by Django 5.2.7 on 2025-10-18 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.TextField(help_text='Descripción legible de la acción')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('objeto', models.CharField(blank=True, help_text='Texto corto indicando el objeto afectado', max_length=200, null=True)),
                ('extra', models.JSONField(blank=True, help_text='Información adicional en JSON (opcional)', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de bitácora',
                'verbose_name_plural': 'Bitácoras',
                'ordering': ['-timestamp'],
            },
        ),
    ]
