# Generated by Django 5.2.7 on 2025-10-21 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auditoria', '0001_initial'),
        ('saas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacora',
            name='tienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras', to='saas.tienda', verbose_name='Tienda (Tenant)'),
        ),
    ]
